/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_aplex_jnidemo_JniNative */

#ifndef _Included_com_example_aplex_jnidemo_JniNative
#define _Included_com_example_aplex_jnidemo_JniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    sayHelloToC
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_aplex_jnidemo_JniNative_sayHelloToC
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_aplex_jnidemo_JniNative
 * Method:    HelloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_aplex_jnidemo_JniNative_HelloFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
